// Mirrors frontend/src/services/api/errors.ts 1:1 — this is the wire contract
// the frontend's mock layer was built against (spec §25):
// `{ success: false, error: { code, message, details? } }`.
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  CLAIM_NOT_OWNED: 'CLAIM_NOT_OWNED',
  CLAIM_NOT_ASSIGNED: 'CLAIM_NOT_ASSIGNED',
  CLAIM_NOT_EDITABLE: 'CLAIM_NOT_EDITABLE',
  CLAIM_EMPTY_ITEMS: 'CLAIM_EMPTY_ITEMS',
  CLAIM_TOTAL_MISMATCH: 'CLAIM_TOTAL_MISMATCH',
  CLAIM_INVALID_TRANSITION: 'CLAIM_INVALID_TRANSITION',
  CLAIM_NOT_CANCELLABLE: 'CLAIM_NOT_CANCELLABLE',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
  REJECTION_REASON_REQUIRED: 'REJECTION_REASON_REQUIRED',
  INFO_REQUEST_MESSAGE_REQUIRED: 'INFO_REQUEST_MESSAGE_REQUIRED',
  INFO_RESPONSE_MESSAGE_REQUIRED: 'INFO_RESPONSE_MESSAGE_REQUIRED',
  CLAIM_NOT_PENDING_APPROVAL: 'CLAIM_NOT_PENDING_APPROVAL',
  CLAIM_NOT_INFO_REQUESTED: 'CLAIM_NOT_INFO_REQUESTED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN_ROLE: 403,
  CLAIM_NOT_FOUND: 404,
  CLAIM_NOT_OWNED: 403,
  CLAIM_NOT_ASSIGNED: 403,
  CLAIM_NOT_EDITABLE: 409,
  CLAIM_EMPTY_ITEMS: 409,
  CLAIM_TOTAL_MISMATCH: 409,
  CLAIM_INVALID_TRANSITION: 409,
  CLAIM_NOT_CANCELLABLE: 409,
  ITEM_NOT_FOUND: 404,
  RECEIPT_NOT_FOUND: 404,
  REJECTION_REASON_REQUIRED: 400,
  INFO_REQUEST_MESSAGE_REQUIRED: 400,
  INFO_RESPONSE_MESSAGE_REQUIRED: 400,
  CLAIM_NOT_PENDING_APPROVAL: 409,
  CLAIM_NOT_INFO_REQUESTED: 409,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};

export class ApiError extends Error {
  code: ErrorCode;
  status: number;
  details?: Record<string, unknown>;

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.status = STATUS_BY_CODE[code];
    this.details = details;
  }
}
